{
 "title": "Fraud Detection API",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(fraud_predictions_total[1m])",
     "legendFormat": "{{outcome}} - v{{model_version}}"
    }
   ]
  },
  {
   "title": "p95 Prediction Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(fraud_prediction_duration_seconds_bucket[1m])) * 1000",
     "legendFormat": "p95 v{{model_version}}"
    }
   ]
  },
  {
   "title": "Fraud vs Legit Predictions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (outcome) (increase(fraud_predictions_total[30m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Total Predictions Served",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(fraud_predictions_total)", "legendFormat": "total" }
   ]
  }
 ]
}