apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fraud-api
  namespace: mlops
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fraud-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - mlops